function onCreate()
	--Triple trouble default
	precacheImage('sonicJUMPSCARE');
	precacheImage('RedVG');
	precacheImage('simplejump');
	precacheImage('Counter');	
	precacheImage('ring');
	precacheImage('STATICNOTE_assets');
	precacheImage('PHANTOMNOTE_assets');
	precacheImage('hitStatic');	
	precacheImage('hi');		
	precacheImage('Phase3/xeno/BackTrees');
	precacheImage('Phase3/Glitch');
	precacheImage('Phase3/Grass');	
	precacheImage('Phase3/NewTitleMenuBG');	
	precacheImage('Phase3/Phase3Static');
	precacheImage('Phase3/Trees');
	precacheImage('Phase3/Trees2');		
	precacheImage('Phase3/xeno/FGTree1');
	precacheImage('Phase3/xeno/FGTree2');
	precacheImage('Phase3/xeno/Grass');	
	precacheImage('pauseScreen/Continue');
	precacheImage('pauseScreen/Exit');
	precacheImage('pauseScreen/pauseRight');
	precacheImage('pauseScreen/Restart');	
	precacheImage('pauseScreen/pauseLeft');
	precacheImage('StartScreens/Circle-triple-trouble');
	precacheImage('StartScreens/Text-triple-trouble');
	precacheImage('BloodSplash');	
	precacheSound('sppok');
	precacheSound('P3Jumps/TailsScreamLOL');
	precacheSound('P3Jumps/KnucklesScreamLOL');
	precacheSound('P3Jumps/EggmanScreamLOL');
	precacheSound('pauseSounds/pause');
	precacheSound('pauseSounds/pausescrollmenu');	
	precacheSound('pauseSounds/puase');
	precacheSound('pauseSounds/unpause');
	precacheSound('hitStatic1');
	precacheSound('Ring');
	precacheSound('sppok');	
	addCharacterToList('BEAST', 'dad');
	addCharacterToList('BEAST2', 'dad');
	addCharacterToList('eggdick', 'dad');
	addCharacterToList('knux', 'dad');
	addCharacterToList('TailsSoul', 'dad');
	addCharacterToList('bf-mirror', 'bf');	
	addCharacterToList('bf', 'bf');
	addCharacterToList('bf-perspective-left', 'bf');
	addCharacterToList('bf-perspective-right', 'bf');
end